### ISSUE TITLE
Add option to display monochrome structure in ACME

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#11]
In this version, once I not check the option "coloured atom" in the CHEMdoodle editor, ACME structure editor would follow. However ACME structure editor itself does not have this option

![image](https://user-images.githubusercontent.com/9064351/72071145-1a39f080-3326-11ea-951c-4a2d02093f77.png)

**Comment by MikeWilliams-UK** [comment]
Fixed by beta-6
