### ISSUE TITLE
Error occurs when I change the function group CH₂ to connect with double bond

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#19]
**Describe the bug**
A clear and concise description [in English] of what the bug is.

**To Reproduce**
![image](https://user-images.githubusercontent.com/9064351/72659179-94d5d080-39f6-11ea-88e4-c2fbb967a774.png)
![image](https://user-images.githubusercontent.com/9064351/72659184-a61edd00-39f6-11ea-9140-299cc2482581.png)
![image](https://user-images.githubusercontent.com/9064351/72659186-b040db80-39f6-11ea-9a67-01bdd373d792.png)
Then error occur

**Expected behavior**
A clear and concise description [in English] of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7/8.1/10 Home/Professional]
 - Word Version [e.g. 2016/O365/2019 Home/Business/Professional]
 - Please also gather system information from "Help" --> "System Info" in Chem4Word Ribbon

**Additional context**

**Comment by deadlyvices** [comment]
Can you please say what the error is?  I cannot reproduce any error messages

**Comment by tomyan112** [comment]
Sorry, I couldn't reproduce it.

**Comment by MikeWilliams-UK** [comment]
Thanks for re testing.
