### ISSUE TITLE
Bundling of the Essential Oil structures with Chem4Word

### ISSUE THREAD

**Issue by deadlyvices** [Chem4Word/Version3-1#2]
When we release Chem4Word we bundle a standard library with it, for illustrative purposes.  I was wondering if there would be any objections to our using the 2100 structure library we have generated as part of the [CEVOpen](https://github.com/petermr/CEVOpen) project.  The structures are very nice indeed and show off our custom display component brilliantly.
If it isn't OK then please let me know.
MAW: Editied to add link to CEVOpen

**Comment by MikeWilliams-UK** [comment]
I have taken the Essential Oils database and re-processed it by utilizing our Library Export and Import functions (with minor tweak to import to calculate Inchi-Key and fetch additional properties).
This version should be used.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices I think that as well as the above there should be a few common ones such as benzene, water etc to "help" the right click convert to chemistry recognize more structures

**Comment by MikeWilliams-UK** [comment]
Essential Oils database is now incorporated
