### ISSUE TITLE
Rendering of double bonds in document does not match ACME

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Chem4Word/Version3-1#25]
Draw the structure shown below, ensuring that the terminal double bond placement is set.

![image](https://user-images.githubusercontent.com/13162784/72683282-dc7b5b80-3acd-11ea-846f-79ebb4c8ad62.png)

**Expected behaviour**
In document rendering should offset the double bond the same as seen in the editor

Operating System: Microsoft Windows 10 Pro 64bit [10.0.18362.0] en-GB
Word Product: Microsoft Office 2016 Professional Plus 64bit [16.0.12325.20298]
Internet Explorer Version: 11.0.18362.592
.Net Framework Runtime: .NET 4.8 (W10 1903) [528040]

**Comment by tomyan112** [comment]
![image](https://user-images.githubusercontent.com/9064351/74415929-442f8700-4e7f-11ea-9ebf-b1289ab7f196.png)
<cml:cml xmlns:conventions="http://www.xml-cml.org/convention/" xmlns:cml="http://www.xml-cml.org/schema" xmlns:cmlDict="http://www.xml-cml.org/dictionary/cml/" xmlns:nameDict="http://www.xml-cml.org/dictionary/cml/name/" xmlns:c4w="http://www.chem4word.com/cml" conventions="convention:molecular">
  <c4w:customXmlPartGuid>15cad641f08e4cfcbddd86d61a54338d</c4w:customXmlPartGuid>
  <cml:molecule id="m1">
    <cml:formula id="m1.f0" concise="C 5 H 5 N 5 O 1" />
    <cml:formula id="m1.f1" convention="chem4word:ResolvedFormula" inline="C5H5N5O" concise="C 5 H 5 N 5 O 1" />
    <cml:formula id="m1.f2" convention="chem4word:ResolvedSmiles" inline="C1=NC2=C(N1)C(=O)N=C(N2)N" concise="C 5 H 5 N 5 O 1" />
    <cml:name id="m1.n1" dictRef="chem4word:CalculatedInchi">1S/C5H5N5O/c6-5-9-3-2(4(11)10-5)7-1-8-3/h1H,(H4,6,7,8,9,10,11)</cml:name>
    <cml:name id="m1.n2" dictRef="chem4word:CalculatedAuxInfo">1/1/N:9,4,5,3,1,7,11,10,6,2,8/rA:11nCNCCCNNOCNN/rB:s1;s2;s3;d4;d1s5;s1;d3;;s5s9;s4d9;/rC:29.3333,-24.4021,0;29.3333,-22.8621,0;30.6669,-22.0921,0;32.0006,-22.8621,0;32.0006,-24.4021,0;30.6669,-25.1721,0;27.9996,-25.1721,0;30.6669,-20.5521,0;34.3704,-23.6321,0;33.4652,-24.8779,0;33.4652,-22.3862,0;</cml:name>
    <cml:name id="m1.n3" dictRef="chem4word:CalculatedInchikey">UYTPUPDQBNUYGX-UHFFFAOYSA-N</cml:name>
    <cml:name id="m1.n4" dictRef="chem4word:ResolvedIupacname">2-amino-3,7-dihydropurin-6-one</cml:name>
    <cml:atomArray>
      <cml:atom id="a1" elementType="C" x2="476.1892" y2="396.1373" />
      <cml:atom id="a2" elementType="N" x2="476.1892" y2="371.1373" />
      <cml:atom id="a3" elementType="C" x2="497.8398" y2="358.6373" />
      <cml:atom id="a4" elementType="C" x2="519.4904" y2="371.1373" />
      <cml:atom id="a5" elementType="C" x2="519.4904" y2="396.1373" />
      <cml:atom id="a6" elementType="N" x2="497.8398" y2="408.6373" />
      <cml:atom id="a7" elementType="N" x2="454.5385" y2="408.6373" />
      <cml:atom id="a8" elementType="O" x2="497.8398" y2="333.6373" />
      <cml:atom id="a9" elementType="C" x2="557.9615" y2="383.6373" />
      <cml:atom id="a10" elementType="N" x2="543.2668" y2="403.8627" />
      <cml:atom id="a11" elementType="N" x2="543.2668" y2="363.4119" />
    </cml:atomArray>
    <cml:bondArray>
      <cml:bond id="b1" atomRefs2="a1 a2" order="S" />
      <cml:bond id="b2" atomRefs2="a2 a3" order="S" />
      <cml:bond id="b3" atomRefs2="a3 a4" order="S" />
      <cml:bond id="b4" atomRefs2="a4 a5" order="D" c4w:placement="Anticlockwise" />
      <cml:bond id="b5" atomRefs2="a5 a6" order="S" />
      <cml:bond id="b6" atomRefs2="a6 a1" order="D" />
      <cml:bond id="b7" atomRefs2="a1 a7" order="S" />
      <cml:bond id="b8" atomRefs2="a3 a8" order="D" />
      <cml:bond id="b9" atomRefs2="a5 a10" order="S" />
      <cml:bond id="b10" atomRefs2="a10 a9" order="S" />
      <cml:bond id="b11" atomRefs2="a9 a11" order="D" />
      <cml:bond id="b12" atomRefs2="a11 a4" order="S" />
    </cml:bondArray>
  </cml:molecule>
</cml:cml>

**Comment by MikeWilliams-UK** [comment]
@tomyan112 this is how the above structure is now rendered in Word.

![image](https://user-images.githubusercontent.com/13162784/75678595-e7590c80-5c85-11ea-9529-6a5018cebe3f.png)

**Comment by MikeWilliams-UK** [comment]
Fixed by beta-6
