### ISSUE TITLE
Default Bond Length setting not working for new drawing

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#27]
**Describe the bug**
Default Bond Length setting is not working if you draw in a table
![image](https://user-images.githubusercontent.com/9064351/73117546-25298d80-3f82-11ea-83ea-ffb45f36de98.png)

![image](https://user-images.githubusercontent.com/9064351/73117673-5a36df80-3f84-11ea-9c93-fdd258dd2cd9.png)

**Desktop (please complete the following information):**
Operating System: Microsoft Windows 10 Pro for Workstations 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 64bit [16.0.12430.20120]
Internet Explorer Version: 11.0.19041.21
.Net Framework Runtime: .NET 4.8 [528372]

**Comment by MikeWilliams-UK** [comment]
Please can you describe in more detail how these drawings were made?
The image above does not describe how they were made.

The bond length setting can be overridden when dragging a bond from an atom using the pencil cursor. During this operation, the bond length should be snapped to multiples of the bond length.

**Comment by tomyan112** [comment]
> Please can you describe in more detail how these drawings were made?
> The image above does not describe how they were made.
> 
> The bond length setting can be overridden when dragging a bond from an atom using the pencil cursor. During this operation, the bond length should be snapped to multiples of the bond length.

I made a video. Please take a minute to watch
https://www.youtube.com/watch?v=u61J_f2equ8

**Comment by MikeWilliams-UK** [comment]
Can you please send a copy of the document to info@chem4word.co.uk as I have just tried to replicate the issue without success.

**Comment by MikeWilliams-UK** [comment]
Cancel the document request.

I have found the problem.
It's nothing to do with tables, which is why I had trouble finding it initially.

The bug is that the editor is not picking up the default value, even though the drop down is correct.
This results in the new drawing having the system default bond length of 20.

When you edit an existing structure, the bond length drop down is set to the average bond length modulus 5. This is why you see 20 when you edit the structure.

**Comment by MikeWilliams-UK** [comment]
@tomyan112 thanks for the video it made it easier to see what was happening.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices I am astonished that this was not picked up in our Alpha testing 🤪

**Comment by deadlyvices** [comment]
This is why we do beta testing!  Well done @tomyan112 !

**Comment by MikeWilliams-UK** [comment]
Fixed in Beta 5
