### ISSUE TITLE
Overlapped text

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#29]
**Describe the bug**

![image](https://user-images.githubusercontent.com/9064351/73326923-df750980-428e-11ea-9754-685a68b9e0b7.png)

**Expected behavior**
A clear and concise description [in English] of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7/8.1/10 Home/Professional]
 - Word Version [e.g. 2016/O365/2019 Home/Business/Professional]
 - Please also gather system information from "Help" --> "System Info" in Chem4Word Ribbon

**Additional context**

**Comment by MikeWilliams-UK** [comment]
Please can you use the "View CML" button on the ribbon to extract the cml.
Then paste it here as **plain text** (not an image) so that we can investigate this.

**Comment by MikeWilliams-UK** [comment]
Is this in ACME or rendered (in document) or both?

**Comment by tomyan112** [comment]
> Is this in ACME or rendered (in document) or both?

This occurs in both. Thus, an alignment feature is needed. 
Flush Left.Creates left-justified caption text.
Centered.Creates centered caption text.
Flush Right.Creates right-justified caption text.
Justified.Creates right-left justified caption text

<cml:cml xmlns:conventions="http://www.xml-cml.org/convention/" xmlns:cml="http://www.xml-cml.org/schema" xmlns:cmlDict="http://www.xml-cml.org/dictionary/cml/" xmlns:nameDict="http://www.xml-cml.org/dictionary/cml/name/" xmlns:c4w="http://www.chem4word.com/cml" conventions="convention:molecular">
  <c4w:customXmlPartGuid>a8df85b7377145c4b30db5daf4194a49</c4w:customXmlPartGuid>
  <cml:molecule id="m1">
    <cml:formula id="m1.f0" concise="C 8 H 16 O 1" />
    <cml:formula id="m1.f1" convention="chem4word:ResolvedFormula" inline="Not requested" concise="C 8 H 16 O 1" />
    <cml:formula id="m1.f2" convention="chem4word:ResolvedSmiles" inline="Not requested" concise="C 8 H 16 O 1" />
    <cml:name id="m1.n1" dictRef="chem4word:CalculatedInchi">Unable to calculate</cml:name>
    <cml:name id="m1.n2" dictRef="chem4word:CalculatedAuxInfo">Unable to calculate</cml:name>
    <cml:name id="m1.n3" dictRef="chem4word:CalculatedInchikey">Unable to calculate</cml:name>
    <cml:name id="m1.n4" dictRef="chem4word:ResolvedIupacname">Not requested</cml:name>
    <cml:atomArray>
      <cml:atom id="a1" elementType="C" x2="396" y2="334.75" />
      <cml:atom id="a2" elementType="C" x2="406" y2="317.4295" />
      <cml:atom id="a3" elementType="C" x2="416" y2="334.75" />
      <cml:atom id="a4" elementType="C" x2="426" y2="317.4295" />
      <cml:atom id="a5" elementType="C" x2="440.1421" y2="331.5716" />
      <cml:atom id="a6" elementType="C" x2="426" y2="297.4295" />
      <cml:atom id="a7" elementType="CH2CH2OH" x2="406" y2="297.4295" />
    </cml:atomArray>
    <cml:bondArray>
      <cml:bond id="b1" atomRefs2="a1 a2" order="S" />
      <cml:bond id="b2" atomRefs2="a2 a3" order="S" />
      <cml:bond id="b3" atomRefs2="a3 a4" order="S" />
      <cml:bond id="b4" atomRefs2="a4 a5" order="S" />
      <cml:bond id="b5" atomRefs2="a4 a6" order="S" />
      <cml:bond id="b6" atomRefs2="a2 a7" order="S" />
    </cml:bondArray>
  </cml:molecule>
</cml:cml>

**Comment by MikeWilliams-UK** [comment]
Thanks for your speedy reply.
We will add this to our backlog.

**Comment by MikeWilliams-UK** [comment]
Let me explain what happens with a Functional Group.

Each functional group consists of a set of components.
In the case of CH2CH2OH these are
- CH2 [Primary]
- CH2
- O
- H

When we display a Functional group a decision is made to render it forwards or backwards
The primary term is placed first such that it is centred about the atom's position (shown with red border)
Then the rest of the terms are either placed to the left (backwards) or right (forwards)
Thus you should end up with something like the images below

|Forwards|Backwards|
|--|--|
| ![image](https://user-images.githubusercontent.com/13162784/73347705-f7915c80-427f-11ea-9ebb-beff5385400b.png) | ![image](https://user-images.githubusercontent.com/13162784/73347749-0aa42c80-4280-11ea-8b30-8f914ca33402.png) |

What has most definitely at fault here is that our automatic system for detecided to render this functional group forwards, when it quite clearly should have been backwards.

**Comment by MikeWilliams-UK** [comment]
Just fixed the decision mechanism to work with functional groups attached to vertical bonds as in your example so that they do not overlap.

![image](https://user-images.githubusercontent.com/13162784/73359431-b8233a00-4298-11ea-9f77-36577aea50f1.png)

We will add the ability to manually override the left or right placement of functional groups at a later stage.

I am expecting to release the beta 5 this weekend

**Comment by MikeWilliams-UK** [comment]
Fixed in Beta 5
