### ISSUE TITLE
Shortcut key does not work in certain situation

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#30]
**Describe the bug**
Shortcut key does not work on certain situation

**To Reproduce**
1. Open a new document
2. Draw a new structure, for example
![image](https://user-images.githubusercontent.com/9064351/73587080-b607e800-44f1-11ea-9ed8-878c5c9d7a7d.png)
3. ctrl+z, nothing happened.
4. select "delete" button, ctrl+z
![image](https://user-images.githubusercontent.com/9064351/73587103-08490900-44f2-11ea-99d7-a14dbfed3201.png)
5. select "draw" button, draw whatever structure, ctrl+z now works as expected.

Side note: could you add ctrl+d for deselection?

**Expected behavior**
ctrl+z should work when whatever button is selected.

**Desktop (please complete the following information):**
Chem4Word 2020 Beta 5 - [3.1.5.7336]
Operating System: Microsoft Windows 10 Pro for Workstations 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 64bit [16.0.12430.20184]
.Net Framework Runtime: .NET 4.8 [528372]

**Comment by MikeWilliams-UK** [comment]
Just tried out <CTRL>+Z and it works fine for me.
Did you have caps lock on or pressing shift as well?
Can you produce a video like you did before to help us find out what's different about what you are doing, please?

The action you are requesting for <Ctrl>+D

**Comment by tomyan112** [comment]
> Just tried out +Z and it works fine for me.
> Did you have caps lock on or pressing shift as well?
> Can you produce a video like you did before to help us find out what's different about what you are doing, please?
> 
> The action you are requesting for +D

https://youtu.be/ssOHaKVY_ys

**Comment by MikeWilliams-UK** [comment]
Thanks for the video.

Is the problem present with all shortcuts like <Ctrl>+C when using the virtual keyboard?
Is the problem present only when using the virtual keyboard?

The editor form has to have focus to receive the key strokes. This may be a bug in how WPF interacts with a virtual keyboard.

@deadlyvices what do you think about this scenario?

**Comment by tomyan112** [comment]
> Thanks for the video.
> 
> Is the problem present with all shortcuts like +C when using the virtual keyboard?
> Is the problem present only when using the virtual keyboard?
> 
> The editor form has to have focus to receive the key strokes. This may be a bug in how WPF interacts with a virtual keyboard.
> 
> @deadlyvices what do you think about this scenario?

I used on-screen keyboard so you can see what is happening. It also presents when using a physical keyboard.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices do you think that this is a keyboard focus issue?

**Comment by deadlyvices** [comment]
Looks like it is.  There are other controls on the window apart from the editor, which nominally receives focus first.

**Comment by MikeWilliams-UK** [comment]
Fixed by beta-6
