### ISSUE TITLE
Fail to add or remove hydrogen automatically

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#31]
![image](https://user-images.githubusercontent.com/9064351/74081793-ddc8f400-4a8d-11ea-93fd-da08bf25dc33.png)

https://youtu.be/VCslE7wpY_I

**Comment by MikeWilliams-UK** [comment]
@deadlyvices can you have a look at this please

**Comment by deadlyvices** [comment]
That looks interesting.  For one, that carbon at the other end of the bond is pentavalent, and that shouldn't have happened.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices they get corrected if you select all and move them, so it's a repaint issue.

**Comment by tomyan112** [comment]
> That looks interesting. For one, that carbon at the other end of the bond is pentavalent, and that shouldn't have happened.

Since you said it is not suppose to be pentavalent or more, this would be interesting to you. Maybe add an optional structure check?
![image](https://user-images.githubusercontent.com/9064351/74412558-adf86280-4e78-11ea-9561-2c24fc6bf3fd.png)
![image](https://user-images.githubusercontent.com/9064351/74412572-b5b80700-4e78-11ea-91ed-a96c2d4b337e.png)

**Comment by deadlyvices** [comment]
You can now intentionally draw a wrong structure but ACME will place a red circle over the over-bonded atoms.

**Comment by MikeWilliams-UK** [comment]
How about a picture @deadlyvices ?

**Comment by MikeWilliams-UK** [comment]
We allow intentional errors as Chem4Word is aimed at the educational market.

**Comment by deadlyvices** [comment]
![image](https://user-images.githubusercontent.com/10074162/74524105-4b55a400-4f16-11ea-95c2-6820d87606fa.png)

**Comment by MikeWilliams-UK** [comment]
Fixed by beta-6
