### ISSUE TITLE
Chose placement of implicit hydrogen

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#32]
Currently the H is placed automatically below the C
![image](https://user-images.githubusercontent.com/9064351/74087983-56e73c00-4acc-11ea-9b3d-23a1c352fabd.png)
Request the option to move the H horizontally.
![image](https://user-images.githubusercontent.com/9064351/74088022-c2310e00-4acc-11ea-8d6b-ac39f0620ba7.png)

**Comment by MikeWilliams-UK** [comment]
Implemented in V3.2
