### ISSUE TITLE
Incompatible with acrobat plugin

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#40]
![image](https://user-images.githubusercontent.com/9064351/75089352-bba59a80-5592-11ea-8e5c-f6436d948f63.png)
Everytime I create pdf with the plugin this error pop up.
![image](https://user-images.githubusercontent.com/9064351/75089322-74b7a500-5592-11ea-8ae5-0734285c4093.png)

**Comment by MikeWilliams-UK** [comment]
@tomyan112 Could you please supply details of how we can obtain the Acrobat Plug In?

Without it we would be totally guessing about why Chem4Word crashes.

**Comment by tomyan112** [comment]
> @tomyan112 Could you please supply details of how we can obtain the Acrobat Plug In?
> 
> Without it we would be totally guessing about why Chem4Word crashes.

It is automatically installed with Adobe Acrobat Pro DC

**Comment by MikeWilliams-UK** [comment]
@tomyan112 further point of clarification.

Does the error occur when you try to create a pdf of any document or just one with our chemistry objects inside it?

**Comment by tomyan112** [comment]
> @tomyan112 further point of clarification.
> 
> Does the error occur when you try to create a pdf of any document or just one with our chemistry objects inside it?

It only occurs when there the document has chemistry objects inside it.

**Comment by deadlyvices** [comment]
Our chemistry objects are simply a content control with DrawingML, inside, and a matching custom XML part in the document.  There is nothing inherently 'chemical'  about either.  So I can only suppose that Acrobat isn't handling the DrawingML.

**Comment by tomyan112** [comment]
> Our chemistry objects are simply a content control with DrawingML, inside, and a matching custom XML part in the document. There is nothing inherently 'chemical' about either. So I can only suppose that Acrobat isn't handling the DrawingML.

It did convert the document. However, it crashed afterward.

**Comment by MikeWilliams-UK** [comment]
@tomyan112 while @deadlyvices is right in what he says it's not the full story.

Chem4Word listens to events such as "DocumentCreated", "DocumentSaved", "DocumentClosed" and many more.
The acid test to see if it is data we have placed in the document or something going wrong in one of our event listeners is to create a document with chemistry in it. Uninstall Chem4Word and see if you get an error.

**Comment by tomyan112** [comment]
> @tomyan112 while @deadlyvices is right in what he says it's not the full story.
> 
> Chem4Word listens to events such as "DocumentCreated", "DocumentSaved", "DocumentClosed" and many more.
> The acid test to see if it is data we have placed in the document or something going wrong in one of our event listeners is to create a document with chemistry in it. Uninstall Chem4Word and see if you get an error.

No errors after I uninstalled Chem4Word.

**Comment by MikeWilliams-UK** [comment]
@tomyan112 thanks for testing this it narrows down where we need to investigate.

**Comment by MikeWilliams-UK** [comment]
Fixed by beta-6
