### ISSUE TITLE
Warning circles are displayed when there is no valence violation

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#48]
![image](https://user-images.githubusercontent.com/9064351/76138017-510a5980-607e-11ea-9631-89e1c86d9435.png)

**Comment by MikeWilliams-UK** [comment]
@deadlyvices I am no chemistry expert, but it looks to me like the valency calculations are not taking charge into account.

**Comment by deadlyvices** [comment]
Yup that's genuine

**Comment by MikeWilliams-UK** [comment]
@deadlyvices do you mean that a genuine bug?

**Comment by deadlyvices** [comment]
Yes.

**Comment by MikeWilliams-UK** [comment]
Fixed in V3.1.8 Beta 8
