### ISSUE TITLE
Default bond length not working in new document

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#53]
**Describe the bug**
Default bond length not working in new document
https://youtu.be/J-Nt7ZCkvcc
Beta-7

**Comment by MikeWilliams-UK** [comment]
This is not a bug, when dragging a bond you can by design create ANY bond length you like, especially when creating a bond between two existing atom like shown in your video.

**Comment by tomyan112** [comment]
> This is not a bug, when dragging a bond you can by design create ANY bond length you like, especially when creating a bond between two existing atom like shown in your video.

I set the default to be 25, but it changed to 75

**Comment by MikeWilliams-UK** [comment]
When you open a drawing the bond length drop down is set to the value closest to the average of the incoming structure.

Again by design.

**Comment by MikeWilliams-UK** [comment]
System is working as designed.
