### ISSUE TITLE
No response after right click the structure if using the ctrl-a shortcut

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#55]
**Describe the bug**
No response after right click the structure if using the ctrl-a shortcut

**To Reproduce**
1. ctrl-a
2. Right Click on the structure
3. Nothing happen

**Expected behavior**
Molecules Properties should show up

**Desktop (please complete the following information):**
Chem4Word 2020 Beta 7 - [3.1.7.7370]

Installation Id: 89f538e4-da23-4cd1-8786-e529e10f7c19
Operating System: Microsoft Windows 10 Pro for Workstations 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 64bit [16.0.12624.20296]
Internet Explorer Version: 11.0.19041.153
.Net Framework Runtime: .NET 4.8 [528372]

**Comment by deadlyvices** [comment]
Is this with one or many molecules in the editor?

**Comment by tomyan112** [comment]
> Is this with one or many molecules in the editor?
one molecule

**Comment by deadlyvices** [comment]
I've just tested it with single and multiple molecules.  With a single molecule, there is no problem.  With multiple molecules, Ctrl-A followed by right-click does nothing, as expected, because it's meaningless to set the property on them

**Comment by MikeWilliams-UK** [comment]
By design

**Comment by tomyan112** [comment]
I realized that you need to right click the structure. I clicked on the highlighted space.
