### ISSUE TITLE
Unable to delete structure

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#56]
**To Reproduce**
1. Draw a structure
2. click ok to render
![image](https://user-images.githubusercontent.com/9064351/77651500-da3eed00-6fa7-11ea-9db7-08ec7522aab6.png)

3.  double click the structure and delete the structure
4. render it
5. Neither "delete" nor "backspace" can delete this thing 
![image](https://user-images.githubusercontent.com/9064351/77651157-56850080-6fa7-11ea-94fb-7da6a96470a8.png)

**Comment by MikeWilliams-UK** [comment]
@tomyan112 I have walked through the code and I can see what is happening.
The editor is returning without a structure, hence an empty container (Word ContentControl) is created and locked. This cant be edited or deleted, except using Developer Tools tab to unlock it.

As I see it we have two choices when the editor returns without a structure.
1. Remove the container for the structure completely.
2. Abort the changes, leaving the previous structure behind.

@deadlyvices I think that the first choice is the most sensible.

**Comment by deadlyvices** [comment]
Agreed.  I just reproduced those steps and I got this:
![image](https://user-images.githubusercontent.com/10074162/77681819-d56d3f80-6f8d-11ea-880d-ea4d0b352ac2.png)
But that was staring with the Draw button, which effectively uses a blank slate.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices agreed to what?

1 or 2

**Comment by deadlyvices** [comment]
To '@deadlyvices I think that the first choice is the most sensible.'

**Comment by MikeWilliams-UK** [comment]
I will implement a fix for these scenarios when I can.
I know exactly what to do it's a case of when I can get enough time to do it.

**Comment by tomyan112** [comment]
> I will implement a fix for these scenarios when I can.
> I know exactly what to do it's a case of when I can get enough time to do it.

Another situation that would not allow you to delete structure.
https://youtu.be/EwjrouPU4kY

**Comment by MikeWilliams-UK** [comment]
@tomyan112 
What key(s) did you use to remove the structure?
Have you unlocked the content control?

**Comment by tomyan112** [comment]
> @tomyan112
> What key(s) did you use to remove the structure?
> Have you unlocked the content control?

Delete.
I did not unlock the content control.
I single clicked the structure in that video.

**Comment by MikeWilliams-UK** [comment]
Thanks @tomyan112 I will have a look at that method of deletion at the same time as fixing the original bug.

**Comment by MikeWilliams-UK** [comment]
@tomyan112 just tried without success to replicate the actions you demonstrated in your video and I can't replicate it using either Delete or Backspace key.

**Comment by tomyan112** [comment]
> @tomyan112 just tried without success to replicate the actions you demonstrated in your video and I can't replicate it using either Delete or Backspace key.
> 

I don't know why.

**Comment by deadlyvices** [comment]
Two versions of Chem4Word running at the same time?  I've seen serious weirdness when this is the case, ands it seems to me like @tomyan112 should check to see whether he has two Ribbon tabs for Chem4Word.

**Comment by tomyan112** [comment]
> Two versions of Chem4Word running at the same time?  I've seen serious weirdness when this is the case, ands it seems to me like @tomyan112 should check to see whether he has two Ribbon tabs for Chem4Word.

Only the latest version as you can see from the video

**Comment by MikeWilliams-UK** [comment]
@deadlyvices you can clearly see only one ribbon in the video.
@tomyan112 can you do help -> system info and verify that all the Chem4Word DLLs loaded have the same version number.

**Comment by tomyan112** [comment]
> @deadlyvices you can clearly see only one ribbon in the video.
> @tomyan112 can you do help -> system info and verify that all the Chem4Word DLLs loaded have the same version number.

Chem4Word 2020 Beta 7 - [3.1.7.7370]

Installation Id: 89f538e4-da23-4cd1-8786-e529e10f7c19
Operating System: Microsoft Windows 10 Pro for Workstations 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 64bit [16.0.12624.20320]
Internet Explorer Version: 11.0.19041.153
.Net Framework Runtime: .NET 4.8 [528372]

Settings Folder: C:\Users\tomya\AppData\Local\Chem4Word.V3
Library Folder: C:\ProgramData\Chem4Word.V3

PlugIns Folder: C:\Program Files (x86)\Chem4Word V3\PlugIns
  Chem4Word.Editor.ACME.dll - [3.1.7.7370]
  Chem4Word.Editor.ChemDoodleWeb800.dll - [3.1.7.7370]
  Chem4Word.Renderer.OoXmlV4.dll - [3.1.7.7370]
  Chem4Word.Searcher.ChEBIPlugin.dll - [3.1.7.7370]
  Chem4Word.Searcher.OpsinPlugIn.dll - [3.1.7.7370]
  Chem4Word.Searcher.PubChemPlugIn.dll - [3.1.7.7370]

.Net Assemblies loaded in memory
  Accessibility, Version=4.0.0.0
  Chem4Word.Core, Version=3.1.7.7370
  Chem4Word.Editor.ACME, Version=3.1.7.7370
  Chem4Word.Editor.ACME, Version=3.1.7.7370
  Chem4Word.Editor.ChemDoodleWeb800, Version=3.1.7.7370
  Chem4Word.Editor.ChemDoodleWeb800, Version=3.1.7.7370
  Chem4Word.Renderer.OoXmlV4, Version=3.1.7.7370
  Chem4Word.Renderer.OoXmlV4, Version=3.1.7.7370
  Chem4Word.Searcher.ChEBIPlugin, Version=3.1.7.7370
  Chem4Word.Searcher.ChEBIPlugin, Version=3.1.7.7370
  Chem4Word.Searcher.OpsinPlugIn, Version=3.1.7.7370
  Chem4Word.Searcher.OpsinPlugIn, Version=3.1.7.7370
  Chem4Word.Searcher.PubChemPlugIn, Version=3.1.7.7370
  Chem4Word.Searcher.PubChemPlugIn, Version=3.1.7.7370
  Chem4Word.Telemetry, Version=3.1.7.7370
  Chem4Word.V3, Version=3.1.7.7370
  CustomMarshalers, Version=4.0.0.0
  IChem4Word.Contracts, Version=3.1.7.7370
  Microsoft.CSharp, Version=4.0.0.0
  Microsoft.Office.Interop.Word, Version=15.0.0.0
  Microsoft.Office.Tools, Version=10.0.0.0
  Microsoft.Office.Tools.Common, Version=10.0.0.0
  Microsoft.Office.Tools.Common.Implementation, Version=10.0.0.0
  Microsoft.Office.Tools.Common.v4.0.Utilities, Version=10.0.0.0
  Microsoft.Office.Tools.Word, Version=10.0.0.0
  Microsoft.Office.Tools.Word.Implementation, Version=10.0.0.0
  Microsoft.ServiceBus, Version=3.0.0.0
  Microsoft.VisualStudio.Tools.Applications.Runtime, Version=10.0.0.0
  Microsoft.VisualStudio.Tools.Applications.ServerDocument, Version=10.0.0.0
  Microsoft.VisualStudio.Tools.Office.Runtime, Version=10.0.0.0
  mscorlib, Version=4.0.0.0
  Newtonsoft.Json, Version=12.0.0.0
  office, Version=15.0.0.0
  PresentationCore, Version=4.0.0.0
  PresentationFramework, Version=4.0.0.0
  PresentationFramework.Aero2, Version=4.0.0.0
  PresentationFramework-SystemXml, Version=4.0.0.0
  PresentationFramework-SystemXmlLinq, Version=4.0.0.0
  SMDiagnostics, Version=4.0.0.0
  System, Version=4.0.0.0
  System.Configuration, Version=4.0.0.0
  System.Core, Version=4.0.0.0
  System.Data, Version=4.0.0.0
  System.Drawing, Version=4.0.0.0
  System.EnterpriseServices, Version=4.0.0.0
  System.IdentityModel, Version=4.0.0.0
  System.Management, Version=4.0.0.0
  System.Net.Http, Version=4.1.1.3
  System.Numerics, Version=4.0.0.0
  System.Runtime.Caching, Version=4.0.0.0
  System.Runtime.Serialization, Version=4.0.0.0
  System.ServiceModel, Version=4.0.0.0
  System.ServiceModel.Internals, Version=4.0.0.0
  System.Transactions, Version=4.0.0.0
  System.Web, Version=4.0.0.0
  System.Web.Services, Version=4.0.0.0
  System.Windows.Forms, Version=4.0.0.0
  System.Xaml, Version=4.0.0.0
  System.Xml, Version=4.0.0.0
  System.Xml.Linq, Version=4.0.0.0
  UIAutomationProvider, Version=4.0.0.0
  UIAutomationTypes, Version=4.0.0.0
  WindowsBase, Version=4.0.0.0
  WindowsFormsIntegration, Version=4.0.0.0

**Comment by MikeWilliams-UK** [comment]
@tomyan112 all the DLLs look fine.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices it would only be developers who have two ribbons as the installer checks to see if an old version is present and halts if it can't be automatically replaced.

**Comment by MikeWilliams-UK** [comment]
@tomyan112 just had another look at your video.

I have observed that
1. Structure is inside a table cell.
2. Adobe add in is enabled.

I will try later with structure inside a table.
Can you try with Adobe add in disabled.

**Comment by Wydna** [comment]
If it helps, I've just created a table with text and structures, and I can delete the structures with no issues, even with the Acrobat add in installed.

**Comment by MikeWilliams-UK** [comment]
Thanks for testing that @Wydna

**Comment by MikeWilliams-UK** [comment]
Fixed in V3.1.8 Beta 8
