### ISSUE TITLE
Double bond disappears when drawn vertically in the editor

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#59]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9064351/77822082-7abd1a80-712a-11ea-997d-42c6968d4a9c.png)

**To Reproduce**
https://youtu.be/YBBl0h7NR0Y

**Comment by MikeWilliams-UK** [comment]
@deadlyvices that looks like a refresh issue.
@tomyan112 if you select the whole structure and move it or change the bond length does the double bond re appear?

**Comment by tomyan112** [comment]
> @deadlyvices that looks like a refresh issue.
> @tomyan112 if you select the whole structure and move it or change the bond length does the double bond re appear?

In both cases, it would reappear.

**Comment by MikeWilliams-UK** [comment]
Thanks @tomyan112 this confirms that it's a cosmetic issue.

**Comment by deadlyvices** [comment]
this is now fixed and will be in the next release.
