### ISSUE TITLE
Anticlockwise double bond drawing issue

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#64]
**Describe the bug**
In editor
![image](https://user-images.githubusercontent.com/9064351/79531838-11d01f00-80a6-11ea-910c-34262780d878.png)
After rendering
![image](https://user-images.githubusercontent.com/9064351/79531814-f8c76e00-80a5-11ea-992b-a0ba73d23b79.png)

**Comment by MikeWilliams-UK** [comment]
@tomyan112 this is how an anticlockwise bond is rendered now.

![image](https://user-images.githubusercontent.com/13162784/80984282-8f758800-8e25-11ea-9740-154c677364a4.png)
