### ISSUE TITLE
1.5 bond is too dense

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#65]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/9064351/80856997-3d93fd00-8c81-11ea-8363-7fcd873d6214.png)
the half bond just becomes little dots

**Describe the solution you'd like**
Below are different density for your consideration
![image](https://user-images.githubusercontent.com/9064351/80857070-c57a0700-8c81-11ea-9056-5e6d9ebb0298.png)
![image](https://user-images.githubusercontent.com/9064351/80857079-d296f600-8c81-11ea-87f8-f7062a546c3f.png)
![image](https://user-images.githubusercontent.com/9064351/80857081-ddea2180-8c81-11ea-900f-264bd2d159bc.png)

**Comment by MikeWilliams-UK** [comment]
@tomyan112 this is what it looks like now

![image](https://user-images.githubusercontent.com/13162784/80916570-6683c300-8d51-11ea-9bbe-f21309e7af3d.png)

Bond to F = Zero
Bond to BR = Half
Rest 1.5 or double

@deadlyvices it was a minor glitch in a refactoring step, which slipped through the net.
