### ISSUE TITLE
Need to uncheck explicit carbon twice for this structure

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#68]
**Describe the bug**
A clear and concise description [in English] of what the bug is.
![image](https://user-images.githubusercontent.com/9064351/82319078-87ac0b00-9a03-11ea-809b-dd79f8152351.png)
![image](https://user-images.githubusercontent.com/9064351/82319157-ab6f5100-9a03-11ea-9207-e013cdb1e657.png)
After first uncheck
![image](https://user-images.githubusercontent.com/9064351/82319179-b3c78c00-9a03-11ea-994f-2e924e785950.png)

**Comment by MikeWilliams-UK** [comment]
@tomyan112 please can you paste the cml as I suspect that the two inner wedges are not sharing the same atom.

**Comment by tomyan112** [comment]
> @tomyan112 please can you paste the cml as I suspect that the two inner wedges are not sharing the same atom.
> 
> This is hinted at by the atom property dialogue only showing one connected bond.

You are right, my bad.
