### ISSUE TITLE
New label not available for immediate display in document

### ISSUE THREAD

**Issue by Wydna** [Chem4Word/Version3-1#73]
**Describe the bug**
When a user adds a new label to a molecule, that label isn't available from the Show As button in the ribbon.

**To Reproduce**
Add a molecule to a document
Click the Edit Labels button
Add a new label, click OK
Click Show As button

New label isn't available in this list

UPDATE:  Added user label doesn't become available even if you save the document and open it again!

**Expected behavior**
I expected the label to be available in the list

System Info
 Chem4Word 2020 Beta 11 - [3.1.11.7495]

Installation Id: 09312673-5ee5-4cce-bfbb-a2e8e87dee30
Operating System: Microsoft Windows 10 Enterprise 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Business 32bit [16.0.13029.20308]
Internet Explorer Version: 11.0.19041.388
.Net Framework Runtime: .NET 4.8 [528372]

**Comment by MikeWilliams-UK** [comment]
@Wydna This is now fixed in the latest beta-11 internal build
![image](https://user-images.githubusercontent.com/13162784/89714310-8c92b200-d995-11ea-8003-6c44a3cbeefc.png)
