### ISSUE TITLE
"Draw" option greyed out

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#9]
**Describe the bug**
"Draw" option greyed out

**Screenshots**
![image](https://user-images.githubusercontent.com/9064351/72042142-85fd6880-32e8-11ea-9b4d-e452841af382.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Word Version O365 version 1912 build 12325.20288

**Version**
CHEM4Word 2020 Beta 2

**Comment by MikeWilliams-UK** [comment]
Please look in your plug ins folder (this can be found from the maintenance tab of the options dialogue) and list the files present.

**Comment by MikeWilliams-UK** [comment]
We have a background process which loads the plugins (which includes the editor), this may have been a bit slow and not fully completed bu the time our ribbon was displayed.
This should be evident by the draw button becoming enable as you start typing (i.e. changing the selection point)

Please could you also post your Chem4Word System Info from the menu item

Help --> System Info

This will enable us to examine the system telemetry which Chem4Word is sending to us.

**Comment by tomyan112** [comment]
> Please look in your plug ins folder (this can be found from the maintenance tab of the options dialogue) and list the files present.

![image](https://user-images.githubusercontent.com/9064351/72052873-e9939000-3300-11ea-970e-3ebc5c982de9.png)

**Comment by tomyan112** [comment]
> We have a background process which loads the plugins (which includes the editor), this may have been a bit slow and not fully completed bu the time our ribbon was displayed.
> This should be evident by the draw button becoming enable as you start typing (i.e. changing the selection point)
> 
> Please could you also post your Chem4Word System Info from the menu item
> 
> Help --> System Info
> 
> This will enable us to examine the system telemetry which Chem4Word is sending to us.

Chem4Word 2020 Beta 2 [3.1.2.7312]

MachineId: 89f538e4-da23-4cd1-8786-e529e10f7c19
Operating System: Microsoft Windows 10 Pro for Workstations 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 64bit [16.0.12325.20288]
Internet Explorer Version: 11.0.19041.1
.Net Framework Runtime: .NET 4.8 [528372]

Settings Folder: C:\Users\tomya\AppData\Local\Chem4Word.V3
Library Folder: C:\ProgramData\Chem4Word.V3

**Comment by MikeWilliams-UK** [comment]
@tomyan112 thanks for the info.

This bug is now fixed https://github.com/Chem4Word/Version3-1/releases/tag/V3.1.3
